# -*- coding: utf-8 -*-

def construct_bool_dict(input_list):
    '''
    Convert the solution generated by both SAT2_Solver and MAIN to dictionary

    Parameters
    ----------
    input_list : nesteed list
        solution in list format

    Returns
    -------
    result : dictionary
        solution in dic format, key is literal, value is assigned value

    '''
    if input_list is None:
        return None
    result = {}
    for i in range(1, len(input_list)+1):
        result[i] = True if input_list[i-1]==1 else False
        result[-i] = not result[i]
    return result